<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

 <!-- ==================== PROJECT INFO ==================== -->

  <groupId>com.resumeanalyzer</groupId>
  <artifactId>ResumeAnalyzerAutomation</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  
  <name>ResumeAnalyzerAutomation</name>
  <description>
        UI and API automation framework for Resume Analyzer application
   </description>

<!-- ==================== PROPERTIES ==================== -->

    <properties>

        <!-- Java -->
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Dependency Versions -->
        <selenium.version>4.33.0</selenium.version>
        <testng.version>7.11.0</testng.version>
        <webdrivermanager.version>6.1.0</webdrivermanager.version>
        <restassured.version>6.0.1</restassured.version>

        <!-- Maven Plugin Versions -->
        <surefire.version>3.5.3</surefire.version>
        <compiler.version>3.14.0</compiler.version>

    </properties>

    <!-- ==================== DEPENDENCIES ==================== -->

    <dependencies>

        <!-- Selenium -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>

        <!-- TestNG -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- WebDriverManager -->
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>${webdrivermanager.version}</version>
        </dependency>

        <!-- REST Assured -->
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>${restassured.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <!-- ==================== BUILD ==================== -->

    <build>

        <plugins>

            <!-- Maven Compiler -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler.version}</version>

                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>

            <!-- Maven Surefire + TestNG -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire.version}</version>

                <configuration>

                    <!-- Default TestNG suite -->
                    <suiteXmlFiles>
                        <suiteXmlFile>testng-regression.xml</suiteXmlFile>
                    </suiteXmlFiles>

                    <!-- Don't append random surefire suffixes -->
                    <useSystemClassLoader>true</useSystemClassLoader>

                    <!-- Test output -->
                    <printSummary>true</printSummary>

                    <!-- Preserve test reports -->
                    <reportsDirectory>
                        ${project.build.directory}/surefire-reports
                    </reportsDirectory>

                </configuration>
            </plugin>

        </plugins>

    </build>

    <!-- ==================== MAVEN PROFILES ==================== -->

    <profiles>

        <!-- ==================== SMOKE ==================== -->

        <profile>

            <id>smoke</id>

            <build>

                <plugins>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${surefire.version}</version>

                        <configuration>

                            <suiteXmlFiles>
                                <suiteXmlFile>
                                    testng-smoke.xml
                                </suiteXmlFile>
                            </suiteXmlFiles>

                        </configuration>

                    </plugin>

                </plugins>

            </build>

        </profile>


        <!-- ==================== REGRESSION ==================== -->

        <profile>

            <id>regression</id>

            <build>

                <plugins>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${surefire.version}</version>

                        <configuration>

                            <suiteXmlFiles>
                                <suiteXmlFile>
                                    testng-regression.xml
                                </suiteXmlFile>
                            </suiteXmlFiles>

                        </configuration>

                    </plugin>

                </plugins>

            </build>

        </profile>

    </profiles>

</project>
